coordinator=true
node-scheduler.include-coordinator=true
http-server.http.port=8080
discovery.uri=http://localhost:8080
catalog.management=static
query.max-memory=512MB
query.max-memory-per-node=512MB
memory.heap-headroom-per-node=512MB
query.max-run-time=2m
query.max-execution-time=90s
query.max-history=100
query.executor-pool-size=16
query.manager-executor-pool-size=4
query.dispatcher-query-pool-size=4
query.max-state-machine-callback-threads=8
query.max-split-manager-callback-threads=8
query.remote-task.max-callback-threads=8
