"""Authentication and TLS against the lab's HTTPS listener (password file + JWT).

Modeled on dbt-trino v1 profile methods none/ldap/jwt and the `cert` option. Uses throwaway
credentials generated by scripts/stack.py; nothing here is a real secret.
"""

import sys
import unittest
from pathlib import Path

from harness import TrinoTestCase, run_sql

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "scripts"))
import stack  # noqa: E402

CA = str(stack.GEN / "ca.crt")
LDAP_USER, LDAP_PASSWORD = "dbt_ldap", stack.USERS["dbt_ldap"]
MODEL = {"models/m.sql": "{{ config(materialized='view') }} select 1 as id"}


class TestAuthentication(TrinoTestCase):
    def https_project(self, **profile):
        base = {"host": "localhost", "port": 8443, "roles": None}
        base.update(profile)
        return self.project("memory", MODEL, profile_overrides=base)

    def test_ldap_with_ca_bundle(self):
        p = self.https_project(method="ldap", user=LDAP_USER, password=LDAP_PASSWORD, cert=CA)
        self.assertIn("All checks passed", p.dbt("debug").output)
        p.dbt("run")
        self.assertEqual(p.type_of("m"), "view")

    def test_wrong_password_is_rejected_and_redacted(self):
        secret = "definitely-wrong-password-0451"
        p = self.https_project(method="ldap", user=LDAP_USER, password=secret, cert=CA)
        result = p.dbt("debug", expect=False)
        self.assertNotIn(secret, result.output)
        log = (p.dir / "logs" / "dbt.log").read_text() if (p.dir / "logs" / "dbt.log").exists() else ""
        self.assertNotIn(secret, log)
        self.assertRegex(result.output.lower(), r"401|unauthorized|authentication|invalid credentials")

    def test_jwt(self):
        p = self.https_project(method="jwt", user="admin", jwt_token=stack.jwt("admin"), cert=CA)
        self.assertIn("All checks passed", p.dbt("debug").output)
        p.dbt("run")

    def test_cert_false_skips_verification(self):
        p = self.https_project(method="ldap", user=LDAP_USER, password=LDAP_PASSWORD, cert=False)
        self.assertIn("All checks passed", p.dbt("debug").output)

    def test_untrusted_certificate_is_rejected(self):
        p = self.https_project(method="ldap", user=LDAP_USER, password=LDAP_PASSWORD)
        result = p.dbt("debug", expect=False)
        self.assertRegex(result.output.lower(), r"certificate|x509|tls")

    def test_password_over_http_is_rejected_before_connecting(self):
        p = self.https_project(method="ldap", user=LDAP_USER, password=LDAP_PASSWORD,
                               http_scheme="http", port=8080)
        result = p.dbt("debug", expect=False)
        self.assertIn("requires http_scheme: https", result.output)
        self.assertNotIn(LDAP_PASSWORD, result.output)

    def test_source_header_and_client_tags(self):
        p = self.project("memory", {"models/marker.sql": "select 'source-marker-7731' as m"},
                         profile_overrides={"client_tags": ["etl", "nightly"]})
        p.dbt("run")
        rows = run_sql(
            "select source from system.runtime.queries "
            "where query like '%source-marker-7731%' and query not like '%system.runtime%'")
        self.assertTrue(rows, "query not found in system.runtime.queries")
        self.assertTrue(all(r[0].startswith("dbt-trino-") for r in rows), rows)


if __name__ == "__main__":
    unittest.main()
